[tool.poetry]
name = "owl"
version = "0.1.0"
description = ""
authors = ["Jakub Rozek <jakub.rozek314@gmail.com>"]
packages = [
    { include = "owl" },
]

[tool.poetry.dependencies]
python = "^3.11"
opencv-python = "^4.7.0.68"
numpy = "^1.24.2"
hilbertcurve = "^2.0.5"
pyaudio = "^0.2.13"

[tool.poetry.scripts]
camera-test = "owl.scripts.camera_test:main"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
mypy = "^1.0.0"
types-pyaudio = "^0.2.16.5"

[[tool.mypy.overrides]]
module = ["cv2.*", "hilbertcurve.*"]
ignore_missing_imports = true


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
